expr_name: 'mbv3-b128-1gpu-scratch'
headless: False

dataloader:
  basepath: "/datasets/imagenet"
  batch_size: 128
  num_workers: 16
  use_dali: True

model:
  type: small
  args:
    width_mult: 1.0
  num_classes: 1000
  pretrained:
    enabled: False
    path: '/workspace/mobilenetv3/pretrained_model.pth'


train:
  base_dir: '/home/jungin500/Workspace/mobilenetv2/outputs'
  precision: 16
  strategy: False
  gpus: 1
  epochs: 20
  ema:
    enabled: False
    decay: 0.9999
  optim:
    lr: 0.02
    weight_decay: 1e-5
    momentum: 0.1
  limit_train_batches: 1.0
  limit_val_batches: 1.0

wandb:
  enabled: True
  project: 'mobilenetv3'
  login_key: ''