name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
    
    # Checkout repository to current directory
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    # Build and push image to container container registry
    - name: Build Docker Image
      run: |
        docker build --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -f - . <<EOF
        FROM nvcr.io/nvidia/pytorch:22.06-py3
        
        RUN set -ex &&\
            \
            python3 -m pip install -r requirements.txt &&\
            rm -rf /workspace/*
        EOF
        
    - name: Push Docker Image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
